### ISSUE TITLE
渲染多张图片时，部分图片可能渲染不出来

### ISSUE THREAD

**Issue by ShenChang618** [Gitjinfeiyang/easy-canvas#12]
第一张是在模拟器上，第二张在实机上
![image](https://user-images.githubusercontent.com/24489287/114391035-94ac8c80-9bc9-11eb-86d8-cb6bb0bcf085.png)
![image](https://user-images.githubusercontent.com/24489287/114391118-ac841080-9bc9-11eb-84ab-5939039a9e02.png)

**Comment by Gitjinfeiyang** [comment]
方便提供下机型、系统版本、以及render嘛
