### ISSUE TITLE
在Taro中使用时，click事件无效了

### ISSUE THREAD

**Issue by Przeblysk** [Gitjinfeiyang/easy-canvas#15]
[复现demo](https://github.com/Przeblysk/easy-canvas-taro-bug-demo)

**Comment by Gitjinfeiyang** [comment]
你好，查看了代码是因为将事件委托给框架导致，请参考https://github.com/Gitjinfeiyang/easy-canvas/blob/master/example/weapp/pages/index/index.js#L233
