### ISSUE TITLE
小程序canvas转换成图片失败？

### ISSUE THREAD

**Issue by Ybaicai** [Gitjinfeiyang/easy-canvas#6]
我调用wx.canvasToTempFilePath失败，报canvasToTempFilePath: fail canvas is empty

**Comment by Gitjinfeiyang** [comment]
https://developers.weixin.qq.com/community/develop/article/doc/000cca357f07e0be99eacad095bc13
查到相关的问题，看看能解决嘛

**Comment by Ybaicai** [comment]
> https://developers.weixin.qq.com/community/develop/article/doc/000cca357f07e0be99eacad095bc13
> 查到相关的问题，看看能解决嘛

已经解决了谢谢
