### ISSUE TITLE
小程序怎么保存图片？

### ISSUE THREAD

**Issue by Small-Years** [Gitjinfeiyang/easy-canvas#7]
如题所示，怎么保存图片，看了demo，不明白怎么保存

**Comment by Gitjinfeiyang** [comment]
微信官方文档 https://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.canvasToTempFilePath.htmlhttps://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.canvasToTempFilePath.html

**Comment by Gitjinfeiyang** [comment]
这部分例子我会再补充下
