### ISSUE TITLE
请问背景色linear-gradient要怎么写才生效

### ISSUE THREAD

**Issue by pengjinlong** [Gitjinfeiyang/easy-canvas#8]
`c(
                                    'view',
                                    {
                                        styles: { backgroundColor: 'linear-gradient(180deg, #FF6A00 0%, #FF9C55 100%)' }, // 样式
                                        attrs: {}, // 属性 比如src
                                        on: {}, // 事件 如click load
                                    },
                                    [c('text', { color: '#fff' }, 'Hello World')]
                            )`
这样写是没有生效的

**Comment by Gitjinfeiyang** [comment]
backgroundColor: ['#eac4a3', '#d0916a']
在示例basic.html中有的，不过目前支持to right方向的，正在看怎么优化这个api，现在有这个需要嘛
